### ISSUE TITLE
KeyError: "FasterRCNN: 'ATSSRPNHead is not in the models registry'"

### ISSUE THREAD

**Issue by ahxiaofengzheng** [mousecpn/Boosting-R-CNN-Reweighting-R-CNN-Samples-by-RPN-s-Error-for-Underwater-Object-Detection#3]
My environment:
![image](https://user-images.githubusercontent.com/81721256/196140373-de498667-7e1a-4641-90a8-29dd70fd2ccd.png)
When I execute the command：
![image](https://user-images.githubusercontent.com/81721256/196141109-3e561e22-6453-4d5e-a46b-adba1a5cbf12.png)
have this error:
KeyError: "FasterRCNN: 'ATSSRPNHead is not in the models registry'"

**Comment by mousecpn** [comment]
how do you install your mmdet?
If you use pip to install it, there will be this error.

**Comment by ahxiaofengzheng** [comment]
@mousecpn this is my Installation method：
![image](https://user-images.githubusercontent.com/81721256/196165324-7920a055-c717-4d77-9f7f-88b4aedc569c.png)

**Comment by mousecpn** [comment]
Please check this doc:
mmdet/models/dense_heads/atss_rpn_head.py

whether it has the class ATSSRPNHead?

**Comment by ahxiaofengzheng** [comment]
I git clone mmdet-2.17.0 from open-mmlab , there is no atss_rpn_head.py under mmdet/models/dense_heads，whether it is possible to copy the entire mmdet folder into mmdet-2.17。
![image](https://user-images.githubusercontent.com/81721256/196170032-e2931de3-1cbc-4da4-8b2f-26d221ad67ae.png)
![image](https://user-images.githubusercontent.com/81721256/196170184-8c2c1338-7272-44df-839d-dc490dcf28cd.png)

**Comment by mousecpn** [comment]
Maybe it can work. You can have a try.
remember to backup.

**Comment by ahxiaofengzheng** [comment]
If i use python setup.py install to install mmdet, i have this error:
![image](https://user-images.githubusercontent.com/81721256/196170947-a7dbb1a2-b212-43dc-a168-746c4c77e5c9.png)

**Comment by mousecpn** [comment]
you should install it first. And then copy the mmdet folder from boostingrcnn into mmdet-2.17

**Comment by ahxiaofengzheng** [comment]
Thanks for your help
