### ISSUE TITLE
The RetinaRPN is not used in your implementations actually, but is introduced in your paper. Is there any difference or conflict?

### ISSUE THREAD

**Issue by Anleeno** [mousecpn/Boosting-R-CNN-Reweighting-R-CNN-Samples-by-RPN-s-Error-for-Underwater-Object-Detection#5]

**Comment by mousecpn** [comment]
> _No description provided._

In the implementation, RetinaRPN is named ATSSRPNHead, though it is nothing to do with ATSS.
Although I want to change the name before I upload it, the pretrained model's use the name ATSSRPNHead, and changing the name will influence the loading of the pretrained checkpoints.

**Comment by Anleeno** [comment]
Thanks for your responses.
